name: Deploy
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "$KNOWN_HOSTS_OLD" > ~/.ssh/known_hosts.old
          chmod 600 ~/.ssh/known_hosts.old
          cat >> ~/.ssh/config <<END
          END
        env:
          KNOWN_HOSTS : ${{ secrets.KNOWN_HOSTS }}
          KNOWN_HOSTS_OLD: ${{ secrets.KNOWN_HOSTS_OLD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
      - name: Print project root directory
        run: |
          ssh $SSH_USER @ $SSH_IP
          cd ${{ secrets.PROJECT_ROOT }}
          ./redeploy.sh
          END
        env:
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          KNOWN_HOSTS_OLD: ${{ secrets.KNOWN_HOSTS_OLD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}